### PR TITLE
LAT-331 Deprecate the Rule weight parameter, add the priority parameter

### PR DESCRIPTION
**Pull request by tmeire**

### CODE REVIEW

**Comment by ynx** [comment]
Still need to update this? https://github.com/acquia/lift-sdk-php/blob/master/examples/Rule.php#L92

**Comment by tmeire** [comment]
Yeah. I changed the rule example and updated the rule entity test.

**Comment by mortenson** [comment]
Thanks @ynx / @blackskad !

I just tried setting the weight after this PR was merged, but haven't been able to successfully create a slot with weighted rules yet. Two questions:

1. Is there an example test out there that shows how this is supposed to work? Has anyone else tried to do this with the API?
2. What does the weight imply? Does a high weight mean that a rule will have less preference than lower weighted rules, or more preference?

**Comment by ynx** [comment]
Notes to capture the discussion between myself and @mortenson:
1. Unfortunately we have no other examples yet.
2. We are obsoleting "weight" so we will be using "priority" from this point (although they are identical right now). Higher priority number means it will be displayed and applied first. For example, you'll want to have your "Everyone" rule to have a low priority of 10, where your "People from Toronto" rule to have a high priority of 30.

We talked about the updates, and will run the script again to see if the problem is resolved. At the meantime, sorry for the incomplete documentation and we'll update it.

**Comment by mortenson** [comment]
Changing weight to priority and using a higher priority for rules I want applied earlier worked! This is working for us, finally. https://github.com/acquia/demo_framework/commit/99545fe8303a2b2cf6a7150b4076b384cec0ff36 was the fix commit. Thanks @ynx !

**Comment by ynx** [comment]
Hooray, @blackskad and @mortenson! FINALLY.

**Pull request merged**
