### PR TITLE
LAT-1105: Update Lift PHP SDK to Symphony 3+ to add compatibility with Drupal 8.4

### PR DESCRIPTION
**Pull request by Infantys**

### CODE REVIEW

**Comment by chilic** [comment]
composer.json
```
"drupal/core": "^8.4",
"acquia/lift-sdk-php": "dev-LAT-1105"
```

result
```
  Problem 1
    - Conclusion: don't install symfony/http-foundation v3.2.13
    - Conclusion: don't install symfony/http-foundation v3.2.12
    - Conclusion: don't install symfony/http-foundation v3.2.11
    - Conclusion: don't install symfony/http-foundation v3.2.10
    - Conclusion: don't install symfony/http-foundation v3.2.9
    - Conclusion: don't install symfony/http-foundation v3.2.8
    - drupal/core 8.4.0 requires symfony/http-foundation ~3.2.8 -> satisfiable by symfony/http-foundation[3.2.x-dev, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.8, v3.2.9].
    - drupal/core 8.4.0-beta1 requires symfony/http-foundation ~3.2.8 -> satisfiable by symfony/http-foundation[3.2.x-dev, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.8, v3.2.9].
    - drupal/core 8.4.0-rc1 requires symfony/http-foundation ~3.2.8 -> satisfiable by symfony/http-foundation[3.2.x-dev, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.8, v3.2.9].
    - drupal/core 8.4.0-rc2 requires symfony/http-foundation ~3.2.8 -> satisfiable by symfony/http-foundation[3.2.x-dev, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.8, v3.2.9].
    - drupal/core 8.4.x-dev requires symfony/http-foundation ~3.2.8 -> satisfiable by symfony/http-foundation[3.2.x-dev, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.8, v3.2.9].
    - drupal/core 8.5.x-dev requires symfony/http-foundation ~3.2.8 -> satisfiable by symfony/http-foundation[3.2.x-dev, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.8, v3.2.9].
    - Conclusion: don't install symfony/http-foundation 3.2.x-dev
    - Conclusion: don't install symfony/http-foundation v3.3.10
    - Conclusion: don't install symfony/http-foundation v3.3.9
    - Conclusion: don't install symfony/http-foundation v3.3.8
    - Conclusion: don't install symfony/http-foundation v3.3.7
    - Conclusion: don't install symfony/http-foundation v3.3.6
    - Conclusion: don't install symfony/http-foundation v3.3.5
    - Conclusion: don't install symfony/http-foundation v3.3.4
    - Conclusion: don't install symfony/http-foundation v3.3.3
    - Conclusion: don't install symfony/http-foundation v3.3.2
    - Conclusion: don't install symfony/http-foundation v3.3.1
    - Conclusion: don't install symfony/http-foundation v3.3.0
    - Conclusion: don't install symfony/http-foundation v3.2.7
    - Conclusion: don't install symfony/http-foundation v3.2.6
    - Conclusion: don't install symfony/http-foundation v3.2.5
    - Conclusion: don't install symfony/http-foundation v3.2.4
    - Conclusion: don't install symfony/http-foundation v3.2.3
    - Conclusion: don't install symfony/http-foundation v3.2.2
    - Conclusion: don't install symfony/http-foundation v3.2.1
    - Conclusion: don't install symfony/http-foundation v3.2.0
    - Conclusion: don't install symfony/http-foundation v3.3.0-RC1
    - Conclusion: don't install symfony/http-foundation v2.8.28
    - Conclusion: don't install symfony/http-foundation v3.2.0-RC2
    - Conclusion: don't install symfony/http-foundation v2.8.27
    - Conclusion: don't install symfony/http-foundation v3.2.0-RC1
    - Conclusion: don't install symfony/http-foundation v2.8.26
    - Conclusion: don't install symfony/http-foundation v3.4.0-BETA1
    - Conclusion: don't install symfony/http-foundation v2.8.25
    - Conclusion: don't install symfony/http-foundation v3.3.0-BETA1
    - Conclusion: don't install symfony/http-foundation v2.8.24
    - Conclusion: don't install symfony/http-foundation v3.2.0-BETA1
    - Conclusion: don't install symfony/http-foundation v2.8.23
    - Installation request for drupal/core ^8.4 -> satisfiable by drupal/core[8.4.0, 8.4.0-alpha1, 8.4.0-beta1, 8.4.0-rc1, 8.4.0-rc2, 8.4.x-dev, 8.5.x-dev].
    - Installation request for drupal/acquia_contenthub dev-8.x-1.x -> satisfiable by drupal/acquia_contenthub[dev-8.x-1.x].
    - drupal/acquia_contenthub dev-8.x-1.x requires acquia/content-hub-php ^1.0.0 -> satisfiable by acquia/content-hub-php[1.0.0, 1.1.0].
    - acquia/content-hub-php 1.0.0 requires symfony/http-foundation ~2.7 -> satisfiable by symfony/http-foundation[2.7.x-dev, 2.8.x-dev, v2.7.0, v2.7.0-BETA1, v2.7.0-BETA2, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.26, v2.7.27, v2.7.28, v2.7.29, v2.7.3, v2.7.30, v2.7.31, v2.7.32, v2.7.33, v2.7.34, v2.7.35, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.0-BETA1, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.28, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - acquia/content-hub-php 1.1.0 requires symfony/http-foundation ~2.7 -> satisfiable by symfony/http-foundation[2.7.x-dev, 2.8.x-dev, v2.7.0, v2.7.0-BETA1, v2.7.0-BETA2, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.26, v2.7.27, v2.7.28, v2.7.29, v2.7.3, v2.7.30, v2.7.31, v2.7.32, v2.7.33, v2.7.34, v2.7.35, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.0-BETA1, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.28, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - Can only install one of: symfony/http-foundation[3.3.x-dev, 2.7.x-dev].
    - Can only install one of: symfony/http-foundation[3.3.x-dev, 2.8.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.0, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.0-BETA1, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.0-BETA2, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.1, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.10, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.11, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.12, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.13, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.14, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.15, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.16, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.17, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.18, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.19, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.2, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.20, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.21, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.22, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.23, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.24, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.25, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.26, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.27, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.28, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.29, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.3, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.30, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.31, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.32, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.33, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.34, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.35, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.4, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.5, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.6, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.7, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.8, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.7.9, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.8.0, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.8.0-BETA1, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.8.1, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.8.10, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.8.11, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.8.12, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.8.13, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.8.14, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.8.15, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.8.16, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.8.17, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.8.18, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.8.19, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.8.2, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.8.20, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.8.21, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.8.22, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.8.3, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.8.4, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.8.5, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.8.6, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.8.7, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.8.8, 3.3.x-dev].
    - Can only install one of: symfony/http-foundation[v2.8.9, 3.3.x-dev].
    - drupal/core 8.4.0-alpha1 requires symfony/http-foundation ^3.2 -> satisfiable by symfony/http-foundation[3.2.x-dev, 3.3.x-dev, 3.4.x-dev, v3.2.0, v3.2.0-BETA1, v3.2.0-RC1, v3.2.0-RC2, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.0-BETA1, v3.3.0-RC1, v3.3.1, v3.3.10, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0-BETA1].
    - Conclusion: don't install symfony/http-foundation 3.4.x-dev
```

@Infantys Could you please check this.

**Review by chilic — APPROVED** [review]
Looks okay

**Comment by Infantys** [comment]
This problem is not related to a specific one. You put drupal 8.4 working with symphony 3 and content-hub-php 1.0.0 working with symfony 2. Therefore, an error occurs.

Replace in your composer.json file:
“drupal/acquia_contenthub”: “dev-8.x-1.x”,
per line
“drupal/acquia_contenthub”: “dev-LAT-1003-test”,

And try again.

**Comment by Infantys** [comment]
Note
acquia/content-hub-d8#174 should be merged before current PR (acquia/content-hub-d8#177 is a test for acquia/content-hub-d8#174).

**Pull request merged**
