### PR TITLE
Revert use of acquia/http-hmac-php fork.

### PR DESCRIPTION
**Pull request by dpagini**
Ran into an issue today with a composer upgrade, detailed at: composer/composer#7764

This essentially a revert of 0f52d855ca85ab8294e20125f

This is because I am using `typhonius/acquia-php-sdk-v2` which requires `acquia/http-hmac-php` and this library, which requires `nickveenhof/http-hmac-php`. The composer 1.7.3 release made this no longer possible. If you are using composer 1.7.3, and try to require these both locally, you will see the problem.
_I think_ the Acquia library has had 8 releases since this initial commit went into this library, so I am hoping any issues that caused the initial fork to be created were since resolved. It looks like this module has testing in place, so we'll see if tests catch any problems.

If this is good enough to go in, would you consider a `0.9.1` release of this library?

### CODE REVIEW

**Comment by Seldaek** [comment]
@dpagini if you require `nickveenhof/http-hmac-php` explicitly in your composer.json I believe it should work as it will allow that packages' replaces to satisfy `typhonius/acquia-php-sdk-v2`'s requirement of `acquia/http-hmac-php`. Would you mind trying that out?

**Comment by dpagini** [comment]
Thanks for the reply, @Seldaek!

That does not seem to have worked for me. In fact, I think you can see my problem if you try this command in a new composer project...

```sh
$ composer require acquia/lift-sdk-php typhonius/acquia-php-sdk-v2 nickveenhof/http-hmac-php:^3.1.3
```

**Comment by Seldaek** [comment]
Ok that is odd, this looks to me like it should resolve.. /cc @stof @naderman

**Comment by dpagini** [comment]
cc: @ynx & @nickveenhof 

Wondering if either of you can weigh in on this one? Also of note is: composer/composer#7767

An alternate fix may be to fix the `nickveenhof/lift-sdk-php` library to correct the `replace` usage maybe?

**Comment by scor** [comment]
Merged suggested change and release 0.9.1 tag (already available at https://packagist.org/packages/acquia/lift-sdk-php)

Before:
```
$ composer require acquia/lift-sdk-php
Using version ^0.9.0 for acquia/lift-sdk-php
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 14 installs, 0 updates, 0 removals
  - Installing paragonie/random_compat (v9.99.99): Downloading (100%)
  - Installing symfony/polyfill-php70 (v1.10.0): Downloading (100%)
  - Installing symfony/polyfill-mbstring (v1.10.0): Downloading (100%)
  - Installing symfony/http-foundation (v3.4.20): Downloading (100%)
  - Installing symfony/polyfill-ctype (v1.10.0): Downloading (100%)
  - Installing symfony/serializer (v3.4.20): Downloading (100%)
  - Installing sarciszewski/php-future (0.4.2): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing nickveenhof/http-hmac-php (3.1.3): Loading from cache
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing ralouphie/getallheaders (2.0.5): Loading from cache
  - Installing guzzlehttp/psr7 (1.5.2): Loading from cache
  - Installing guzzlehttp/guzzle (6.3.3): Loading from cache
  - Installing acquia/lift-sdk-php (0.9.0): Downloading (100%)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
symfony/serializer suggests installing doctrine/annotations (For using the annotation mapping. You will also need doctrine/cache.)
symfony/serializer suggests installing doctrine/cache (For using the default cached annotation reader and metadata cache.)
symfony/serializer suggests installing psr/cache-implementation (For using the metadata cache.)
symfony/serializer suggests installing symfony/config (For using the XML mapping loader.)
symfony/serializer suggests installing symfony/property-access (For using the ObjectNormalizer.)
symfony/serializer suggests installing symfony/property-info (To deserialize relations.)
symfony/serializer suggests installing symfony/yaml (For using the default YAML mapping loader.)
nickveenhof/http-hmac-php suggests installing silex/silex (~1.3.0)
nickveenhof/http-hmac-php suggests installing symfony/psr-http-message-bridge (~0.1.0)
nickveenhof/http-hmac-php suggests installing symfony/security (~3.0.0)
nickveenhof/http-hmac-php suggests installing zendframework/zend-diactoros (~1.3.5)
guzzlehttp/guzzle suggests installing psr/log (Required for using the Log middleware)
acquia/lift-sdk-php suggests installing ramsey/uuid (A PHP 5.4+ library for generating RFC 4122 version 1, 3, 4, and 5 universally unique identifiers (UUID))
Writing lock file
Generating autoload files
```

After releasing 0.9.1:
```
Stephanes-MacBook-Pro:lift-sdk3 stephane.corlosquet$ composer require acquia/lift-sdk-php
Using version ^0.9.1 for acquia/lift-sdk-php
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 14 installs, 0 updates, 0 removals
  - Installing paragonie/random_compat (v9.99.99): Loading from cache
  - Installing symfony/polyfill-php70 (v1.10.0): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.10.0): Loading from cache
  - Installing symfony/http-foundation (v3.4.20): Loading from cache
  - Installing symfony/polyfill-ctype (v1.10.0): Loading from cache
  - Installing symfony/serializer (v3.4.20): Loading from cache
  - Installing sarciszewski/php-future (0.4.2): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing acquia/http-hmac-php (3.4.0): Loading from cache
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing ralouphie/getallheaders (2.0.5): Loading from cache
  - Installing guzzlehttp/psr7 (1.5.2): Loading from cache
  - Installing guzzlehttp/guzzle (6.3.3): Loading from cache
  - Installing acquia/lift-sdk-php (0.9.1): Downloading (100%)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
symfony/serializer suggests installing doctrine/annotations (For using the annotation mapping. You will also need doctrine/cache.)
symfony/serializer suggests installing doctrine/cache (For using the default cached annotation reader and metadata cache.)
symfony/serializer suggests installing psr/cache-implementation (For using the metadata cache.)
symfony/serializer suggests installing symfony/config (For using the XML mapping loader.)
symfony/serializer suggests installing symfony/property-access (For using the ObjectNormalizer.)
symfony/serializer suggests installing symfony/property-info (To deserialize relations.)
symfony/serializer suggests installing symfony/yaml (For using the default YAML mapping loader.)
acquia/http-hmac-php suggests installing silex/silex (~1.3.0)
acquia/http-hmac-php suggests installing symfony/psr-http-message-bridge (~0.1.0)
acquia/http-hmac-php suggests installing symfony/security (~3.0.0)
acquia/http-hmac-php suggests installing zendframework/zend-diactoros (~1.3.5)
guzzlehttp/guzzle suggests installing psr/log (Required for using the Log middleware)
acquia/lift-sdk-php suggests installing ramsey/uuid (A PHP 5.4+ library for generating RFC 4122 version 1, 3, 4, and 5 universally unique identifiers (UUID))
Writing lock file
Generating autoload files
```

difference is moving from 
  - Installing nickveenhof/http-hmac-php (3.1.3): Loading from cache
to 
  - Installing acquia/http-hmac-php (3.4.0): Loading from cache


Thanks @dpagini !

**Pull request merged**
